### PR TITLE
EBMEDS-1192: Remove Redis

### PR DESCRIPTION
**Pull request by joonatanv**
Removes Redis from engine as per [EBMEDS-1192](https://jira.duodecim.fi/browse/EBMEDS-1192).

---

- schema changes: https://github.com/ebmeds/schemas/pull/27
- api-gateway changes: https://github.com/ebmeds/api-gateway/pull/86
- engine changes: https://github.com/ebmeds/engine/pull/261

### CODE REVIEW

**Comment by joonatanv** [comment]
This'd probably be the prime time for me to get ebmeds-docker actually running locally as well 😅 
I'll bother Tomi about getting me into Quay -- unless I already have an account that I can't recall.

@SkylarPhx what are the implications of reading the user configuration from a file in api-gateway? The path of the file, as well as the user mode, are also set in api-gateway as .env variables. I'd assume that there's a need for installations that don't have direct access to the internals of api-gateway to somehow wire it all up from this repository?

**Review by SkylarPhx — APPROVED** [review]
The changes look good and it seems that the `user.json` is already mapped with the `api-gateway`.

The `EBMEDS_API_GATEWAY_USER_JSON_PATH` is for internal use of the `api-gateway` container. That is fine, no need to make any changes here as the `user.json` is already mapped from the root directory of the `ebmeds-docker`.

Also, all available environment variables can be overridden in `config.env` e.g. by adding the `EBMEDS_USER_MODE` will override the `api-gateway` env-defaults. This overridden is global – affecting all services.

**Comment by joonatanv** [comment]
So no further changes needed then? 😮

**Comment by SkylarPhx** [comment]
No, but you may want to test it with local builds. Also, there is no need to restart the swarm if the root directory `user.json` is modified.

**Review by Tomkinen — APPROVED** [review]

**Pull request merged**
